Update TERMS-OF-USE.md
mobilecoinfoundation/fog pull request #125
Opened 2021-08-16 20:37 UTC by the-real-adammork

Soundtrack of this PR: [link to song that really fits the mood of this PR]()

### Motivation

< The motivation for the changes in this PR. "Currently we...", "This is needed because..." >

### In this PR
* < Additions, removals, fixes, features >

< Ticket status, e.g. "fixes #issue number" > 

### Future Work
* < Out of scope non-goals for this PR >
* < These should be links to tickets. If the tickets do not exist, make them. >

2021-08-16 20:38 UTC, garbageslam approved these changes

2021-08-16 20:52 UTC, sugargoat approved these changes

2021-08-17 20:45 UTC, jcape requested changes
This PR points users at the invalid "buymobile.us" website, and includes a start date of "[August __, 2021]"

2021-08-17 20:46 UTC, the-real-adammork commented
> This PR points users at the invalid "buymobile.us" website, and includes a start date of "[August __, 2021]"

good catch, Ill change this and update

2021-08-18 03:33 UTC, jcape commented
Superseded by #127

2021-08-18 03:33 UTC, closed without merging