configure sql timeouts
mobilecoinfoundation/fog pull request #143
Opened 2021-12-07 03:06 UTC by garbageslam

Brings updates related to SQL timeouts to the release 1.1.2 branch

2021-12-07 16:36 UTC, jgreat requested changes
Timings look good,  Can we get these setting exposed as config values with these setting as default (ideally as env vars, but I'll take cli args, or both).  

We may need to tune and adjust, and it would be nice to not have to cut a release to do that.

2021-12-07 19:17 UTC, garbageslam commented
@jgreat let's review this version first, then i'll backport a version of that to 1.1.2, cause it's a larger change to make this configurable everywhere and i'm trying to do it in the cleanest way

https://github.com/mobilecoinfoundation/mobilecoin/pull/1204

2021-12-08 07:01 UTC, wjuan-mob approved these changes

2021-12-10 00:51 UTC, garbageslam commented
This is now a backport of the PR merged into master for this, I think it should be ready to go

2021-12-13 18:48 UTC, jcape approved these changes

2021-12-13 21:57 UTC, jgreat approved these changes

2021-12-13 21:58 UTC, merged